name: My First Workflow

on:
  push:
  pull_request:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello, GitHub Actions!"

  say-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Print Bye Message
        run: echo "Bye from GitHub Actions!"