name: My First Workflow

on:
  push:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, GitHub Actions!"

  say-bye:
    needs: say-hello
    runs-on: ubuntu-latest
    steps:
      - name: Print Bye Message
        run: echo "Bye from 2nd Job"